export const GLOSSARY: Record<string, Record<string, Record<string, string>>> = {
  "es-en": {
    "automotive": {
      "defensa": "bumper",
      "facia": "bumper",
      "bomper": "bumper",
      "parrilla": "grill",
      "caja": "trunk",
      "cajuela": "trunk",
      "baúl": "trunk",
      "capó": "hood",
      "cofre": "hood",
      "bonete": "hood",
      "guardafangos": "fender",
      "salpicadera": "fender",
      "lodera": "fender",
      "llanta": "tire",
      "goma": "tire",
      "troca": "truck",
      "camión": "truck",
      "rines": "rims",
      "volante": "steering wheel",
      "timón": "steering wheel",
      "guía": "steering wheel",
      "marbete": "vehicle registration",
      "balatas": "brake pads",
      "pantallas": "headlights",
      "focos": "headlights"
    },
    "medical_vns": {
      "chequeo general": "general checkup",
      "medicina para el dolor": "pain medication",
      "pastillas": "pills / medication",
      "mamografía": "mammogram",
      "rayos x": "X-ray",
      "cáncer": "cancer",
      "receta médica": "prescription",
      "autorización previa": "prior authorization",
      "referido": "referral",
      "copago": "copay",
      "deducible": "deductible",
      "proveedor de atención médica": "healthcare provider",
      "seguro médico": "health insurance",
      "plan médico": "health insurance",
      "cobertura": "coverage",
      "VNS Health": "VNS Health",
      "Medicaid": "Medicaid",
      "Medicare": "Medicare",
      "sala de emergencias": "emergency room (ER)",
      "cuidados paliativos": "hospice care",
      "calentura": "fever",
      "gripa": "flu / cold",
      "catarro": "cold",
      "azúcar alta": "high blood sugar / diabetes"
    },
    "legal_us": {
      "juez": "judge",
      "abogado": "attorney",
      "licenciado": "attorney",
      "fiscal": "prosecutor",
      "ministerio público": "prosecutor / DA",
      "testigo": "witness",
      "jurado": "jury",
      "veredicto": "verdict",
      "demanda": "lawsuit",
      "pleito": "lawsuit",
      "demandante": "plaintiff",
      "demandado": "defendant",
      "acusado": "defendant",
      "audiencia": "hearing",
      "corte": "court",
      "juzgado": "court",
      "fianza": "bail",
      "libertad condicional": "probation",
      "orden de cateo": "search warrant",
      "orden de arresto": "arrest warrant",
      "citatorio": "subpoena",
      "denuncia": "police report / complaint",
      "ticket": "citation / ticket",
      "boleto": "citation / ticket",
      "declaración de culpabilidad": "guilty plea",
      "apelar": "to appeal"
    },

    "business_ames": {
      "remitly": "remitly",
      "wester union": "wester union",
      "moneygram": "moneygram",
      "spectrum": "spectrum",
      "verizon": "verizon",
      "at&t": "at&t",
      "spectrum bill": "spectrum bill",
      "verizon bill": "verizon bill",
      "at&t bill": "at&t bill",
      "Department of Labor of New York": "Department of Labor of New York",
      "New York State Tax Department": "New York State Tax Department",
      "NYS DOL": "New York State Tax Department",
      "NYS Tax Department": "New York State Tax Department"
    },

    "veterinary_banfield": {
      "pulgas": "fleas",
      "garrapatas": "ticks",
      "parásitos del corazón": "heartworms",
      "prevención de parásitos": "parasite prevention",
      "desparasitante": "dewormer",
      "plan de bienestar": "Optimum Wellness Plan",
      "examen físico integral": "comprehensive physical exam",
      "vacuna contra la rabia": "rabies vaccine",
      "vacuna contra el moquillo": "distemper vaccine",
      "vacuna contra bordetella": "Bordetella vaccine",
      "desparasitación": "deworming",
      "análisis de heces": "fecal exam",
      "análisis de sangre": "blood work",
      "cuidado dental": "dental care",
      "esterilización": "spay",
      "castración": "neuter",
      "enfermedad renal": "kidney disease",
      "diabetes felina": "feline diabetes",
      "medicamento para pulgas y garrapatas": "flea and tick medication",
      "receta veterinaria": "veterinary prescription",
      "microchip": "microchip",
      "cita veterinaria": "veterinary appointment",
      "historial médico": "medical records",
      "cartilla de vacunación": "vaccine records",
      "enfermedad periodontal": "periodontal disease",
      "cirugía veterinaria": "veterinary surgery",
      "pata": "paw",
      "patas": "paws",
      "orejas": "ears",
      "uñas": "nails",
      "corte de uñas": "nail trim",
      "almohadillas de las patas": "paw pads",
      "dientes": "teeth",
      "ojos": "eyes",
      "cola": "tail",
      "hocico": "muzzle",
      "pelaje": "fur",
      "castrar": "neuter / fix",
      "esterilizar": "spay / fix",
      "operación para no tener crías": "getting fixed",
      "croquetas": "kibble / dry food",
      "recortar": "groom / trim",
      "baño y corte": "grooming",
      "chucho": "dog"
    }
  }
};
