export interface CountryCode {
    code: string;
    country: string;
    label: string;
    uniqueKey: string;
}

export const COUNTRY_CODES: CountryCode[] = [
    { code: "+971", country: "AE", label: "🇦🇪 +971", uniqueKey: "+971-AE" },
    { code: "+54", country: "AR", label: "🇦🇷 +54", uniqueKey: "+54-AR" },
    { code: "+43", country: "AT", label: "🇦🇹 +43", uniqueKey: "+43-AT" },
    { code: "+61", country: "AU", label: "🇦🇺 +61", uniqueKey: "+61-AU" },
    { code: "+32", country: "BE", label: "🇧🇪 +32", uniqueKey: "+32-BE" },
    { code: "+591", country: "BO", label: "🇧🇴 +591", uniqueKey: "+591-BO" },
    { code: "+55", country: "BR", label: "🇧🇷 +55", uniqueKey: "+55-BR" },
    { code: "+1", country: "CA", label: "🇨🇦 +1", uniqueKey: "+1-CA" },
    { code: "+56", country: "CL", label: "🇨🇱 +56", uniqueKey: "+56-CL" },
    { code: "+86", country: "CN", label: "🇨🇳 +86", uniqueKey: "+86-CN" },
    { code: "+57", country: "CO", label: "🇨🇴 +57", uniqueKey: "+57-CO" },
    { code: "+506", country: "CR", label: "🇨🇷 +506", uniqueKey: "+506-CR" },
    { code: "+53", country: "CU", label: "🇨🇺 +53", uniqueKey: "+53-CU" },
    { code: "+420", country: "CZ", label: "🇨🇿 +420", uniqueKey: "+420-CZ" },
    { code: "+49", country: "DE", label: "🇩🇪 +49", uniqueKey: "+49-DE" },
    { code: "+45", country: "DK", label: "🇩🇰 +45", uniqueKey: "+45-DK" },
    { code: "+1", country: "DO", label: "🇩🇴 +1", uniqueKey: "+1-DO" },
    { code: "+593", country: "EC", label: "🇪🇨 +593", uniqueKey: "+593-EC" },
    { code: "+20", country: "EG", label: "🇪🇬 +20", uniqueKey: "+20-EG" },
    { code: "+503", country: "SV", label: "🇸🇻 +503", uniqueKey: "+503-SV" },
    { code: "+34", country: "ES", label: "🇪🇸 +34", uniqueKey: "+34-ES" },
    { code: "+358", country: "FI", label: "🇫🇮 +358", uniqueKey: "+358-FI" },
    { code: "+33", country: "FR", label: "🇫🇷 +33", uniqueKey: "+33-FR" },
    { code: "+44", country: "GB", label: "🇬🇧 +44", uniqueKey: "+44-GB" },
    { code: "+30", country: "GR", label: "🇬🇷 +30", uniqueKey: "+30-GR" },
    { code: "+502", country: "GT", label: "🇬🇹 +502", uniqueKey: "+502-GT" },
    { code: "+504", country: "HN", label: "🇭🇳 +504", uniqueKey: "+504-HN" },
    { code: "+36", country: "HU", label: "🇭🇺 +36", uniqueKey: "+36-HU" },
    { code: "+972", country: "IL", label: "🇮🇱 +972", uniqueKey: "+972-IL" },
    { code: "+91", country: "IN", label: "🇮🇳 +91", uniqueKey: "+91-IN" },
    { code: "+39", country: "IT", label: "🇮🇹 +39", uniqueKey: "+39-IT" },
    { code: "+81", country: "JP", label: "🇯🇵 +81", uniqueKey: "+81-JP" },
    { code: "+254", country: "KE", label: "🇰🇪 +254", uniqueKey: "+254-KE" },
    { code: "+82", country: "KR", label: "🇰🇷 +82", uniqueKey: "+82-KR" },
    { code: "+212", country: "MA", label: "🇲🇦 +212", uniqueKey: "+212-MA" },
    { code: "+52", country: "MX", label: "🇲🇽 +52", uniqueKey: "+52-MX" },
    { code: "+234", country: "NG", label: "🇳🇬 +234", uniqueKey: "+234-NG" },
    { code: "+505", country: "NI", label: "🇳🇮 +505", uniqueKey: "+505-NI" },
    { code: "+31", country: "NL", label: "🇳🇱 +31", uniqueKey: "+31-NL" },
    { code: "+47", country: "NO", label: "🇳🇴 +47", uniqueKey: "+47-NO" },
    { code: "+64", country: "NZ", label: "🇳🇿 +64", uniqueKey: "+64-NZ" },
    { code: "+507", country: "PA", label: "🇵🇦 +507", uniqueKey: "+507-PA" },
    { code: "+51", country: "PE", label: "🇵🇪 +51", uniqueKey: "+51-PE" },
    { code: "+48", country: "PL", label: "🇵🇱 +48", uniqueKey: "+48-PL" },
    { code: "+351", country: "PT", label: "🇵🇹 +351", uniqueKey: "+351-PT" },
    { code: "+595", country: "PY", label: "🇵🇾 +595", uniqueKey: "+595-PY" },
    { code: "+40", country: "RO", label: "🇷🇴 +40", uniqueKey: "+40-RO" },
    { code: "+7", country: "RU", label: "🇷🇺 +7", uniqueKey: "+7-RU" },
    { code: "+966", country: "SA", label: "🇸🇦 +966", uniqueKey: "+966-SA" },
    { code: "+46", country: "SE", label: "🇸🇪 +46", uniqueKey: "+46-SE" },
    { code: "+41", country: "CH", label: "🇨🇭 +41", uniqueKey: "+41-CH" },
    { code: "+27", country: "ZA", label: "🇿🇦 +27", uniqueKey: "+27-ZA" },
    { code: "+90", country: "TR", label: "🇹🇷 +90", uniqueKey: "+90-TR" },
    { code: "+1", country: "US", label: "🇺🇸 +1", uniqueKey: "+1-US" },
    { code: "+598", country: "UY", label: "🇺🇾 +598", uniqueKey: "+598-UY" },
    { code: "+58", country: "VE", label: "🇻🇪 +58", uniqueKey: "+58-VE" },
];

export const DEFAULT_COUNTRY_KEY = "+1-US";